apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mlflow
  name: mlflow
  namespace: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - image: localhost:32000/mlflow:latest
          args:
            - --host=0.0.0.0
            - --port=5000
            - --backend-store-uri=sqlite:///memory
            - --default-artifact-root=s3://mlflow
          name: mlflow
          envFrom:
            - secretRef:
                name: mlflow-artifacts-credentials
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
          ports:
            - name: http
              containerPort: 5000
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: mlflow
spec:
  selector:
    app: mlflow
  ports:
    - name: http
      targetPort: http
      port: 5000
      nodePort: 32001
  type: NodePort
