{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mlflow-operator.serviceAccountName" . }}
  labels:
    {{- include "mlflow-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mlflow-operator.serviceAccountName" . }}
  labels:
    {{- include "mlflow-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "mlflow-operator.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "mlflow-operator.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
